# Generated by Django 5.2 on 2026-06-22 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "저자",
                "verbose_name_plural": "저자 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "장르",
                "verbose_name_plural": "장르 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True, max_length=800)),
                (
                    "published_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(default="ko", max_length=10)),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("tfidf_vector_json", models.TextField(blank=True, default="{}")),
                ("tfidf_computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("open_library", "Open Library"),
                            ("kakao", "Kakao Books API"),
                            ("naver", "Naver Books API"),
                            ("manual", "수동 입력"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="books.author"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="books.genre"
                    ),
                ),
            ],
            options={
                "verbose_name": "도서",
                "verbose_name_plural": "도서 목록",
                "ordering": ["-rating_count", "-average_rating"],
            },
        ),
        migrations.CreateModel(
            name="UserBookInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("read", "읽음"),
                            ("want_to_read", "읽고 싶어요"),
                            ("reading", "읽는 중"),
                            ("rated", "평가함"),
                            ("liked", "좋아요"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "독서 기록",
                "verbose_name_plural": "독서 기록 목록",
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["-average_rating"], name="books_book_average_571518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["language"], name="books_book_languag_ea595e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbookinteraction",
            unique_together={("user", "book", "interaction_type")},
        ),
    ]
