# Generated by Django 5.2 on 2026-06-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "tier",
                    models.CharField(
                        choices=[("high", "높음"), ("mid", "중간"), ("low", "낮음")],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "algorithm_version",
                    models.CharField(default="tfidf-v1", max_length=20),
                ),
                ("ml_flag", models.BooleanField(default=False)),
                ("judgment_hash", models.CharField(blank=True, max_length=64)),
                ("context_page", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "추천 이력",
                "verbose_name_plural": "추천 이력 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="recommendat_user_id_c1d076_idx",
                    ),
                    models.Index(
                        fields=["book", "tier"], name="recommendat_book_id_824be0_idx"
                    ),
                ],
            },
        ),
    ]
